### ISSUE TITLE
Different highlight for the matched pattern under the cursor

### ISSUE THREAD

**Issue by kminh** [haya14busa/incsearch.vim#101]
First of all, this plugin is a must-have!

Is it possible to set the `IncSearch` highlight group for the matched pattern under cursor (when pressing `n` or `N`)? Similar to how this plugin does it: https://github.com/junegunn/vim-oblique

Thank you.

**Comment by haya14busa** [comment]
Thanks.

You can use IncSearchOnCursor. Please see :h IncSearchOnCursor

**Comment by kminh** [comment]
That seems to affect only the character under the cursor, and only affect the first match.

**Comment by haya14busa** [comment]
>  affect only the character under the cursor,

I cannot reproduce it. Can you give me a screenshot and cofing?

> only affect the first match.

I cannot get it. The matched pattern under cursor must be the fist match, right?
Do you mean the IncSearchOnCursor highlight doesn't move with `<Tab>`/`<S-tab>`?

**Comment by kminh** [comment]
I mean when you press `n`/`N`. Please see the below screencast (sorry about the quality):
![incsearch-highlight-current-match-2015-11-27_03 16 33](https://cloud.githubusercontent.com/assets/6402124/11430199/9759fb64-94b5-11e5-858b-3d47fff7676b.gif)

**Comment by haya14busa** [comment]
You can write `n`/`N` extention plugin on your own and use `<Plug>(incsearch-nohl)`.

incsearch.vim won't privide `n`/`N` extentions. 

>	NOTE: |<Plug>(incsearch-nohl-n)| stuff are just aliases to
	`<Plug>(incsearch-nohl)n` except |n| doesn't get remapped, so the
	basic behaviour is completely same as the default one.
