### ISSUE TITLE
Bug with substitute

### ISSUE THREAD

**Issue by ernestorenanche** [haya14busa/incsearch.vim#103]
When I use the substitution command all the occurrences  will be highlighted. If I move into the file , the highlighting does not disappear. I have to use one of the keys mapped to the plugin and then use a motion.

For instance, with
```
:s/old/new<CR>$
```
every `old` will be highlighted. With
```
:s/old/new<CR>nN$
```
the highlighting disappears but I have two more keystrokes.

**Comment by haya14busa** [comment]
We cannot execute command after substitution, so incsearch.vim cannot support it.

If you are ok with some side-effect, you can do it with below mappings.

```vim
noremap <Plug>(my_:) :
map <buffer> : <Plug>(incsearch-nohl)<Plug>(my_:)
```
