### ISSUE TITLE
I'd like to use <Plug>(incsearch-stay-backword)

### ISSUE THREAD

**Issue by toshi32tony3** [haya14busa/incsearch.vim#104]
いつもありがたく使わせて頂いています。リクエストです。
以下についてforward検索用のマッピングが提供されていますが、backward版も欲しいです。

> \<Plug\>(incsearch-stay)
> \<Plug\>(incsearch-fuzzy-stay)
> \<Plug\>(incsearch-fuzzyspell-stay)
> \<Plug\>(incsearch-migemo-stay)

■備考
\<Plug\>(incsearch-stay)については以下のマッピングで代替できていますが、
他の3つについては同様にして代替できるかわかりませんでした。
> noremap <silent> <expr> g? incsearch#go({'command' : '?', 'is_stay' : 1})

**Comment by haya14busa** [comment]
PRして頂いて申し訳ないのですがすべて新たに`<Plug>`マッピングを定義するのではなくユーザ側で定義していただきたいです．
例えばmigemoだとこんな感じです. (他の例もほぼ同様)

```
noremap <silent><expr> g? incsearch#go(incsearch#config#migemo#make({'command': '?', 'is_stay': 1}))
```

stayは基本的に動かない，もし動くとしたら前向きだろうという考えでbackwardについては有用なケースが思いつかないのでデフォルトで提供してません．
もしなにかデフォルトにしてもおもしろそうなユースケースがあれば少々PRを変更して取り込むかも知れませんが，基本的にはユーザ定義でやってもらう方針です．


issueの返信が遅くなったばかりにすいません...

**Comment by toshi32tony3** [comment]
回答ありがとうございます！年の瀬にすみませんでした。

提示して頂いた方法でfuzzy, fuzzyspell, migemo, easymotionについて動作確認しました。
私がやりたかったことは満たせましたので、全く問題ありません。

> stayは基本的に動かない，もし動くとしたら前向きだろうという考えでbackwardについては有用なケースが思いつかないのでデフォルトで提供してません．

私は、単純にforward検索とbackward検索を使い分けたかったのです。
n/N/\<Tab\>/\<S-TAB\>の移動方向を常に同一方向にしたい人は現状のstayのみで満足するのだと思います。
（が、私はそうでなかったので困った次第でした）

■備考
fuzzy, fuzzyspell, migemoの場合、入力が少ない時にマッチする候補が多いためカーソルがガシャガシャ動いて画面が切り替わるのが嫌でした。そのため、stayを好んで使っています。
