### ISSUE TITLE
When I use search-offset, the bell will be rung

### ISSUE THREAD

**Issue by toshi32tony3** [haya14busa/incsearch.vim#105]
オフセットを付加した検索開始した時に、ベルが鳴ります。

> /Neo/s+1
> /Neo/e

以下のオプションを使用するとベルが鳴らなくなるため、ノーマルモードで不要な\<Esc\>が使用されているようです。

> set belloff=esc

**Comment by haya14busa** [comment]
この branch を試して頂けますか? https://github.com/haya14busa/incsearch.vim/tree/fix-errorbell

**Comment by toshi32tony3** [comment]
fix-errorbellブランチで修正されていることを確認しました。対応ありがとうございます！

**Comment by haya14busa** [comment]
マスターにマージしました．報告ありがとうございました！
