### ISSUE TITLE
Question: Can I move the cursor on the first match after typing a pattern and <CR>

### ISSUE THREAD

**Issue by toshi32tony3** [haya14busa/incsearch.vim#108]
いつもお世話になっております！以下のようなことをしたいのですが、実現できていません。
どのように設定すれば良いか、ご教示願えないでしょうか。
- やりたいこと
  1. 検索パターン入力中はカーソルを動かしたくない
  2. <Esc>で検索をキャンセルした時はカーソルを動かしたくない
  3. <CR>で検索パターン確定後、カーソルが検索開始位置から変わっていなければ  
     最初のマッチにカーソルを移動したい

以下のようなことを試したのですが、上手く設定できませんでした。
- 試したこと
  - IncSearchExecutePre/IncSearchExecuteでカーソル位置が変わっていなければcall feedkeys('n')  
    →stay検索時、パターン入力後<CR>してカーソルが動かない場合は上記autocmdが動かなかった
  - IncSearchEnter/IncSearchLeaveで最新の検索履歴が変化しており、  
    かつカーソル位置が変わっていなければcall feedkeys('n')  
    →検索履歴更新タイミングの都合？により取得した履歴が常に一致してしまった  
    →検索履歴数で試しても同様  
    →検索レジスタ(@/)の場合、パターン入力後にキャンセルした場合でもレジスタが更新されていた  
    (検索キャンセル時はIncSearchLeave後に検索レジスタの内容が戻される？)

``` VimL
  noremap <silent> <expr> / incsearch#go({'command' : '/', 'is_stay' : 1})
  noremap <silent> <expr> ? incsearch#go({'command' : '?', 'is_stay' : 1})
  autocmd MyAutoCmd User IncSearchEnter
        \   let g:incsearch#lastSearchHist = histget("search", -1)
        \ | let g:incsearch#lastCurPos     = getcurpos()
  autocmd MyAutoCmd User IncSearchLeave
        \   if g:incsearch#lastSearchHist !=# histget("search", -1) &&
        \      g:incsearch#lastCurPos     ==  getcurpos()
        \ | call feedkeys('n', 't')
        \ | endif
```

**Comment by haya14busa** [comment]
`<Plug>(incsearch-stay)` で，最初のマッチに移動したい場合は `<Tab>` を一回押してから`<CR>`してください．
