### ISSUE TITLE
Finish search without changing @/

### ISSUE THREAD

**Issue by wilywampa** [haya14busa/incsearch.vim#110]
Is there a way to keep the cursor at the match when exiting `incsearch.vim` without changing the current search pattern/highlighting? Here's what I mean using regular vim search:

![incsearch](https://cloud.githubusercontent.com/assets/4472522/13761999/54670e98-e9f9-11e5-941a-3c129d8ed5b3.gif)

What I'd like is for all the new matches to be highlighted using `incsearch.vim` while searching, leave the cursor at the match at the end, and switch back to the original highlighting. In other words it would be like using `<C-c>` to exit `incsearch.vim` but keeping the cursor position instead of canceling everything.

I tried using the `IncSearchEnter` and `IncSearchLeave` autocommands to save `@/` before using `incsearch.vim` and restore it afterwards, but `incsearch.vim` sets `@/` after triggering `IncSearchLeave`.

Ideally this would be a map that could be set in `g:incsearch_cli_key_mappings`.

**Comment by haya14busa** [comment]
Sorry for the late response.

Hmm... incsearch.vim doesn't aim to yet another search command, but aims to the improvement of `/`.
Changing @/ is natural. I think it's possible to implement it, but it's not simple and I don't have any motivation to do this.
