### ISSUE TITLE
Beginning 7.4.1615, Getting a "variable nested too deep for displaying error"

### ISSUE THREAD

**Issue by raymond-w-ko** [haya14busa/incsearch.vim#111]
Beginning with Vim 7.4.1577, made a change regarding how partial variables work. There was also some other patches associated with that since then.

I'm not sure if the problem is a fault of what Vim changed to partials or there is something that can be worked around in incsearch.vim.

```function incsearch#_go[5]..<SNR>105_get_input[12]..148[4]..146[1]..162[9]..161[10]..160[23]..159[22]..158[8]..131[2]..186[1]..<SNR>116_call[3]..329[1]..<SNR>150_on_searching[2]..<SNR>150_on_char[26]..<SNR>150_move_cursor[19]..<SNR>108_dictfunction, line 1 Vim(let):E724: variable nested too deep for displaying```

**Comment by adelarsq** [comment]
Still occurs with 7.4.1627:
![a](https://cloud.githubusercontent.com/assets/430272/13920002/5985461e-ef4f-11e5-9c2a-d1d9edd6b131.png)

**Comment by raymond-w-ko** [comment]
I upgraded to Vim 7.4.1646 and the latest master of incsearch.vim, and everything works again. I will now close.

**Comment by haya14busa** [comment]
Thank for the report and confirmation!
