### ISSUE TITLE
<esc> on / shows control character and does not immediately cancel search

### ISSUE THREAD

**Issue by Alok** [haya14busa/incsearch.vim#114]
It's about midway through the video in the bottom search bar.
I have `/` mapped to `incsearch-forward`

https://asciinema.org/a/7mfrfi8pir0yg82ywfqny33lj

EDIT: I just saw that video and it's orange for some odd reason, so here's a screenshot:

![screenshot 2016-03-26 22 48 56](https://cloud.githubusercontent.com/assets/8325708/14064033/f9126000-f3a4-11e5-8268-3a2d1c194522.png)

**Comment by haya14busa** [comment]
I guess it's neovim problem but i'm not sure.

**Comment by Alok** [comment]
Turns out I had a conflicting mapping for <esc> that was interfering because of the timeout delay.
