### ISSUE TITLE
Vimの7.4.1635のバージョンで<Plug>(incsearch-forward)はハイライトをしない

### ISSUE THREAD

**Issue by kazufukurou** [haya14busa/incsearch.vim#115]
Vimの7.4.1635のバージョンで`<Plug>(incsearch-forward)`あとの入力ときハイライトは出ません。
`<Plug>(incsearch-stay)`はハイライトをします。
Vimの7.4.1074のバージョンでハイライトは動いてます。

**Comment by haya14busa** [comment]
報告ありがとうございます．vimの問題かもしれないのでvimを1639以降にアップデートしていただけるでしょうか? http://vim-jp.org/blog/2016/03/23/take-care-of-patch-1577.html

**Comment by kazufukurou** [comment]
はい、1669にアップデートすると問題が解けました。ありがとうございます。
