### ISSUE TITLE
Unable to paste previous search command using <c-r>/

### ISSUE THREAD

**Issue by pmcRTR** [haya14busa/incsearch.vim#121]
When using the incsearch plugin, after I type a <code>/</code> to open the search bar, I am unable to paste in the contents of the last search register by typing <code>Ctrl-R /</code>

Without incsearch it works with no problems.

With the incsearch plugin enabled, typing / to get the search command line and then typing <code>Ctrl-R /</code> to paste in the last pattern instead inserts: <code>"\c</code>

Running a <code>:registers</code> command still shows me that the / register has the expected content it's just that I can't paste it into the incsearch search line. :(

I am running Vim 8.0.008 and latest incsearch.vim plugin.

**Comment by haya14busa** [comment]
sorry for the late reply but I fixed it. #124

Thank you for the report ! :+1:
