### ISSUE TITLE
Typing a double quote seems to cause freezing

### ISSUE THREAD

**Issue by Alok** [haya14busa/incsearch.vim#122]
I have '/' mapped to incsearch-forward. If I type just `"` at the start of my search, the whole plugin freezes.

**Comment by haya14busa** [comment]
I cannot reproduce it. please make a minimal reproduction step.

For example, what the output of `:verbose cmap "` ?

**Comment by Alok** [comment]
`:verbose cmap "` says that there's no mapping for  `"`. I profiled incsearch by searching for a `"` and immediately quitting after. It took almost 5 seconds to do anything, even in a file that contained nothing but a single `"`. [Here's a gist of the profile.](https://gist.github.com/d4716e3a55bc2c0b5b4fe5c53a23daa7)
