### ISSUE TITLE
ctrl+f (show history) not work with this plugin

### ISSUE THREAD

**Issue by wizicer** [haya14busa/incsearch.vim#126]
I just used to <kbd>ctrl+f</kbd> to show search history, it not work with this plugin.

Current workaround is to execute `:unmap /`.

**Comment by haya14busa** [comment]
You can type <kbd>q/</kbd> in normal mode to show search history instead.

It's difficult to support `<C-f>` in incsearch.vim.

**Comment by wizicer** [comment]
Good tip, sure this should be a better workaround, and it's acceptable.
