### ISSUE TITLE
Broken paste in some terminal emulators

### ISSUE THREAD

**Issue by ntkme** [haya14busa/incsearch.vim#131]
When incsearch.vim is activated, paste in **some terminal emulators** (e.g. Terminal.app on OS X) will only insert the first character in clipboard. This issue is introduced since vim [patch 8.0.0210: no support for bracketed paste](https://github.com/vim/vim/commit/ec2da36ca48b40c0654b32a8d2c9f52e796daa5e), which added the support of bracketed paste to vim.

**Comment by ntkme** [comment]
`:set t_BE=` would fix this issue, but it would be nice if `incsearch.vim` can work out of the box.

**Comment by haya14busa** [comment]
Thank you for the investigation.
it's definitely better to support bracketed paste mode in incsearch.vim.

Currently I'm not sure how to fix it at all, so helps are really welcome.
Maybe, getchar(1) with bracketed paste mode doesn't work...?

**Comment by ntkme** [comment]
From the latest vim documentation:

> When the 't_BE' option is set then 't_BE' will be sent to the terminal when entering "raw" mode and 't_BD' when leaving "raw" mode. The terminal is then expected to put 't_PS' before pasted text and 't_PE' after pasted text. This way Vim can separate text that is pasted from characters that are typed. The pasted text is handled like when the middle mouse button is used, it is inserted literally and not interpreted as commands.

> When the cursor is in the first column, the pasted text will be inserted before it. Otherwise the pasted text is appended after the cursor position. This means one cannot paste after the first column.  Unfortunately Vim does not have a way to tell where the mouse pointer was.

>Note that in some situations Vim will not recognize the bracketed paste and you will get the raw text.  **In other situations Vim will only get the first pasted character and drop the rest**, e.g. when using the "r" command. If you have a problem with this, disable bracketed paste by putting this in your .vimrc:

``` viml
set t_BE=
````

> If this is done while Vim is running the 't_BD' will be sent to the terminal to disable bracketed paste.

I think a potential solution is to store the value of 't_BE' and unset it when entering incsearch, and then restore the value when leaving it.
