### ISSUE TITLE
Feature Request: use * search for current visually selected text

### ISSUE THREAD

**Issue by xu-cheng** [haya14busa/incsearch.vim#135]
Though, * search is convenient. It will usually fail to select long words or sentence. Therefore, it is desirable to visual select text first then search them.

It would be nice if this plugin can support this feature. This feature can also be extended to support other key bindings like `#`, `g*` and `g#`. At the same time, it would be nice to keep other orthogonal feature like nohlsearch compatible with it.

Some relevant document: http://vim.wikia.com/wiki/Search_for_visually_selected_text

**Comment by haya14busa** [comment]
Please use asterisk.vim

Incsearch.vim also has help for using it together nicely.

**Comment by xu-cheng** [comment]
Thanks for the tip. However, I'm not sure how to make nohlsearch and asterisk.vim coexisted. Specially how to make below config compatible with each other?

```
map n  <Plug>(incsearch-nohl-n)
map N  <Plug>(incsearch-nohl-N)
map *  <Plug>(incsearch-nohl-*)
map #  <Plug>(incsearch-nohl-#)
map g* <Plug>(incsearch-nohl-g*)
map g# <Plug>(incsearch-nohl-g#)
```

and 

```
map *   <Plug>(asterisk-*)
map #   <Plug>(asterisk-#)
map g*  <Plug>(asterisk-g*)
map g#  <Plug>(asterisk-g#)
map z*  <Plug>(asterisk-z*)
map gz* <Plug>(asterisk-gz*)
map z#  <Plug>(asterisk-z#)
map gz# <Plug>(asterisk-gz#)
```

**Comment by haya14busa** [comment]
See :h g:incsearch#auto_nohlsearch

	    map *   <Plug>(incsearch-nohl)<Plug>(asterisk-*)
	    map g*  <Plug>(incsearch-nohl)<Plug>(asterisk-g*)
	    map #   <Plug>(incsearch-nohl)<Plug>(asterisk-#)
	    map g#  <Plug>(incsearch-nohl)<Plug>(asterisk-g#)

	    map z*  <Plug>(incsearch-nohl0)<Plug>(asterisk-z*)
	    map gz* <Plug>(incsearch-nohl0)<Plug>(asterisk-gz*)
	    map z#  <Plug>(incsearch-nohl0)<Plug>(asterisk-z#)
	    map gz# <Plug>(incsearch-nohl0)<Plug>(asterisk-gz#)
<

**Comment by xu-cheng** [comment]
Many thanks.
