### ISSUE TITLE
always using n for searching forward, and N backward

### ISSUE THREAD

**Issue by lgy87** [haya14busa/incsearch.vim#139]
Hi haya14busa,

my vimrc:
```
nnoremap <expr> n 'Nn'[v:searchforward]
nnoremap <expr> N 'nN'[v:searchforward]
```
it works well.
but now i use incsearch.vim, it doesn't work.

Thank you.

**Comment by haya14busa** [comment]
use `let g:incsearch#consistent_n_direction = 1`

:h g:incsearch#consistent_n_direction

**Comment by lgy87** [comment]
Thanks very much.

**Comment by lgy87** [comment]
Thanks a lot.
