### ISSUE TITLE
Find C++ function/method defenition

### ISSUE THREAD

**Issue by sittim** [haya14busa/incsearch.vim#140]
Can this plugin be used to do this?

https://vi.stackexchange.com/questions/12284/fuzzy-find-c-function-defenition

Is it possible to do something like:

`.{0,20}(pattern)(.{0,100}) \{`

where (patten) is the fuzzy pattern that becomes part of the regex?

**Comment by haya14busa** [comment]
https://github.com/haya14busa/incsearch.vim#converter-feature

You can define converter to do the job.
