### ISSUE TITLE
Cannot use backspace in search pattern

### ISSUE THREAD

**Issue by suo** [haya14busa/incsearch.vim#145]
As suggested by the docs, I have added the following to my `.vimrc`
```
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)
```
Everything works, except when I type:
```
/foo
```
Then try to hit backspace, I get this error:
```
E486: Pattern not found: foo<C-\>e31_BackwardDeleteChar()
```

The same problem doesn't happen with regular incsearch.

**Comment by liningsen** [comment]
I got a similar problem. When in search mode, backspace turns into kb and delete key turns into kD
