### ISSUE TITLE
Add compatibility with vim-indexed-search

### ISSUE THREAD

**Issue by khughitt** [haya14busa/incsearch.vim#21]
[vim-indexed-search](https://github.com/henrik/vim-indexed-search) is a nifty plugin which displays the current and total number of search matches found.

It also does this by wrapping `/`.

Is there any possibility that support could be added to either work along-side of vim-indexed-search, or, to provide a similar functionality?

**Comment by habitullence** [comment]
@haya14busa this helped me too, thanks. I don't see indexed search built in, do I need to add anything to config?

**Comment by haya14busa** [comment]
You can use https://github.com/haya14busa/incsearch-index.vim to shwo the current and total number of search matches.
