### ISSUE TITLE
Impossible to enter <C-i/j/m> in search

### ISSUE THREAD

**Issue by pernatiy** [haya14busa/incsearch.vim#49]
Using <C-v> (at least in linux), without incsearch.vim, I can enter any character without it's special meaning (i.e. it will be treated as character, not keypress). So typing '/<C-v><C-m>' I can search for <C-m> character, which otherwise will be treated as <Enter> key. Looks like "incsearch.vim" doesn't have any type of escape character for it's command line interface.

**Comment by systemmonkey42** [comment]
Any movement on this?  I find it extremely bizarre to be unable to search for <tab> characters without the ctrl-v functionality.

**Comment by haya14busa** [comment]
I'm sorry to keep you waiting. I implemented `<C-v>` on dev branch and I'll merge it into master soon.

**Comment by systemmonkey42** [comment]
This works really well.   Some keys are strange.  
- Ctrl-V Ctrl-J produces "^@", and
- Ctrl-V Ctrl-H produces "<80>kb"

**Comment by haya14busa** [comment]
> Ctrl-V Ctrl-J produces "^@", and

I guess this is expected behavior. I get same result with Vim default command line.

> Ctrl-V Ctrl-H produces "<80>kb"

I cannot reproduce this.
I guess it may be related with Vim's version handling.

What version of vim do you use?
