### ISSUE TITLE
mappings with <expr> and <SID>  cause 'E117 Unkown function' error

### ISSUE THREAD

**Issue by kealthou** [haya14busa/incsearch.vim#51]
vim-easymotion and vim-over, which provide the similar function and use vital's over module don't have the problem, or more like the mappings are ignored in those `<Plug>(easymotion-sn)` and `OverCommandLine` respectively, for good or bad. 

```
set runtimepath+=~/.vim/bundle/incsearch.vim
map / <Plug>(incsearch-forward)
cnoremap <expr> <C-h> <SID>a()
cnoremap <expr> s <SID>a()
function! s:a()
endfunction
```

FYI, vim-smartinput and lexima.vim use this kind of mapping.

**Comment by haya14busa** [comment]
I fixed this issue in dev branch. so please wait for a while.

**Comment by haya14busa** [comment]
Merged it into master :tada:
