### ISSUE TITLE
Mappings and paste

### ISSUE THREAD

**Issue by jordwalke** [haya14busa/incsearch.vim#58]
First off, excellent plugin. Thank you for building it. I just have some issues that prevent me from using it:

- When pasting while in search mode, from Macvim (or I imagine gvim as well) it doesn't paste - it only prints ` "+gP`.
- I have other key mappings that were intended to be activated while searching (`cmap`s for things like `c-e`/`c-f`/`c-a`/`c-b` so that I can use emacs/mac style cursors without using the arrow keys. All of these seem to be removed now that I installed this plugin. Is there any way to continue to use all of those custom mappings with `incsearch`?

**Comment by nzbart** [comment]
I am using this plugin on Windows, and can confirm that pasting is broken for me, too.

To reproduce:

1. Copy some text into the system clipboard from another application.
2. Switch to Vim and press '/' to enter search mode.
3. Try to paste the clipboard contents using shift+ins. This usually works, but is broken by incsearch.

**Comment by haya14busa** [comment]
As for the pasting issue, please see #35

For the other key mappings, please give me the out put of `:cnoremap` and `:echo g:incsearch#vim_cmdline_keymap` (Expect: 1).

**Comment by jordwalke** [comment]
Thank you for the help. I was using

    imap <C-a> <Esc>I
    map! <c-e> <End>
    map! <c-f> <Right>
    map! <c-b> <Left>
    map! <c-d> <Delete>

When doing `:cnoremap`, I saw:

    c  <C-A>         <Home>
    !  <C-B>         <Left>
    !  <C-D>         <Del>
    !  <C-E>         <End>
    !  <C-F>         <Right>
    c  <C-H>         <C-C>:w<CR>
    c  <C-L>         <C-C>
    !  <C-N>       * <Down>
    !  <C-P>       * <Up> 

`c-a` worked, but nothing that I configured with `map!` worked anymore.

1. I switched everything to use `cmap` and now it works, but there's one remaining problem
2. Using `cmap` to map `<c-l>` to `<Esc>` when in search mode doesn't seem to work at all.
3. Is there a way to disable the standard `c-j`/`c-k` mappings so that `inc-search` does not even attempt to map them? They interfere with other mappings.

**Comment by haya14busa** [comment]
> c-a worked, but c-b (or anything using map!) did not work.

Thank you for the report, @jordwalke . Hmm.. it's interesting. I'll look into int later :)

> Using cmap to map `<c-l>` to `<Esc>` when in search mode doesn't seem to work at all.
Is there a way to disable the standard c-j/c-k mappings so that inc-search does not even attempt to map them? They interfere with other mappings.

Currently, I didn't provide option to supress incsearch's custom mappings like `<c-l>`, `<c-j>` and `<c-k>`,
but you can overwrite these mappings with `:IncSearchNoreMap`

Please see `:h :IncSearchNoreMap`.

**Comment by haya14busa** [comment]
> c-a worked, but c-b (or anything using map!) did not work.

It turns out to be a bug of using library which doesn't handle `map!`. I'll fix it later. Thanks again :+1:

**Comment by haya14busa** [comment]
I fixed this issue. Please update incsearch.vim :tada:

**Comment by jordwalke** [comment]
What was the issue? Seems to work very awesomely now.

**Comment by jordwalke** [comment]
Though, I'm having trouble mapping `c-l` to close the search mode. Here's what I tried:

```vim
  let g:incsearch#emacs_like_keymap = 1
  " From the example:
  augroup incsearch-keymap
      autocmd!
      autocmd VimEnter * call s:incsearch_keymap()
  augroup END
  function! s:incsearch_keymap()
      IncSearchNoreMap <c-l> <Esc>
      IncSearchNoreMap <c-l> <C-c>
  endfunction

```

**Comment by haya14busa** [comment]
> Though, I'm having trouble mapping c-l to close the search mode. Here's what I tried:

I cannot reproduce it. Can you make a minimal reproduction steps with minimal vimrc?

**Comment by jordwalke** [comment]
Okay, if you observed that `c-l` example working correctly, then it must be something else about my setup. Thanks for letting me know where to look.
