### ISSUE TITLE
Highlighting issue with no cursor motion asterick command

### ISSUE THREAD

**Issue by WscriChy** [haya14busa/incsearch.vim#63]
I have a mapping like this

    map * <Plug>(incsearch-nohl)<Plug>(asterisk-z*)

It supposed that right after any motion current search highlighting disappears. But it requires one more motion to do that.
Small example: The cursor is in the middle of any word in normal mode, press '*k', the highlighting must disappear, but no. You need one more motion, like 'k'.

**Comment by haya14busa** [comment]
Use `<Plug>(incsearch-nohl0)`. Please read :h g:incsearch#auto_nohlsearch

```vim
map z*  <Plug>(incsearch-nohl0)<Plug>(asterisk-z*)
```
