### ISSUE TITLE
Add fuzzy search

### ISSUE THREAD

**Issue by balta2ar** [haya14busa/incsearch.vim#64]
How about adding forward/backward fuzzy search similar to the one in https://github.com/junegunn/vim-oblique?

**Comment by haya14busa** [comment]
Thanks for the request @balta2ar :+1:

I also consider to add fuzzy search feature, but this is not only for fuzzy search but also for fully customizable conversion of input text. #57 

I actually implement fuzzy search in this branch https://github.com/haya14busa/incsearch.vim/tree/converter , but I have to improve it more.

I'll work on #57 for this feature, so I closed this issue.
