### ISSUE TITLE
n / N broken

### ISSUE THREAD

**Issue by jasonkuhrt** [haya14busa/incsearch.vim#65]
When I try https://github.com/haya14busa/incsearch.vim#automatic-nohlsearch It causes `n` and `N` to do nothing. How could this be?

**Comment by haya14busa** [comment]
I cannot reproduce this. Please write more detail information and minimal vimrc to reproduce it.

**Comment by jasonkuhrt** [comment]
Ok

**Comment by haya14busa** [comment]
please reopen with more detail information

**Comment by jasonkuhrt** [comment]
Will do. I've been using `spacemacs` lately so may never need this resolved.
