### ISSUE TITLE
任意のテキストが入力された状態で開始することができる機能がほしい

### ISSUE THREAD

**Issue by osyo-manga** [haya14busa/incsearch.vim#68]
動作イメージとしては `:Incsearch hoge` と入力すれば `/hoge` が入力された状態で開始されるようなユーザコマンドです。
現状、 `<Plug>(incsearch-forward)hoge` というようなキー呼び出しを行えば同等のことを行えるのですがこれだとちょっとパフォーマンスが悪いのです…（これは vital-over 側の都合
なので `s:cli.get()` に対して直接開始時のテキストが渡せるような仕組みがあれば嬉しいです。

**Comment by osyo-manga** [comment]
あ、あと具体的にやりたいこととしては以下のようなマッピングになります。

```vim
map <expr> <C-n> "\<Plug>(incsearch-forward)".@/
```

**Comment by osyo-manga** [comment]
ちょっとタイトル変えました。
ほしいのは『ユーザコマンド』というよりかは『任意のテキストが入力された状態で開始できる機能』になります。
なので以下のように `<expr>` を使ったものでもよさそうです。

```vim
map <expr> <C-n> incsearch#forward_expr(@/)
```

**Comment by haya14busa** [comment]
欲しいとは前々から僕も思ってたんですが進捗状況がよろしくなかった顔.

コマンドを提供するかは考え中ですが, 少なくとも関数呼び出しでできるようにはしたいと思います.

**Comment by osyo-manga** [comment]
きたい

**Comment by haya14busa** [comment]
関数呼び出しによるデフォルトパターン指定の対応を dev ブランチ https://github.com/haya14busa/incsearch.vim/tree/dev にて行いました．

#### 使用法

[:h incsearch-config-pattern](https://github.com/haya14busa/incsearch.vim/blob/23a60eb414174c1e163a152d5c2d9e76afc47dcc/doc/incsearch.txt#L450-L455)

```vim
noremap <expr> <C-n> incsearch#go({'pattern': histget('/', -1)})
```

offsetなどに対応するために`histget`を使ってますがもちろん@/でも使えます．
よければお時間あるときにでも試していただけると嬉しいです．


あともし使っていればの話ですが `incsearch#forward()`や`incsearch#backward()`といった関数は廃止されて `incsearch#go([{config}])`に統一されたので注意してください
す．

**Comment by osyo-manga** [comment]
ありがとうございます。
手元でもいい感じに動いています。

**Comment by haya14busa** [comment]
ありがとうございます！
ユーザコマンドに関しては今のところは実装は見送るつもりです．そのうち使っていてコマンドあれば便利そうだったらまた別issueでやりまする

**Comment by haya14busa** [comment]
マスターにﾏｯｼﾞしました

**Comment by osyo-manga** [comment]
benri

**Comment by haya14busa** [comment]
yosa. ありがとうございましたー
