### ISSUE TITLE
incsearch doesn't work with indexed-search

### ISSUE THREAD

**Issue by timfeirg** [haya14busa/incsearch.vim#70]
there's this plugin called [indexed-search](https://github.com/henrik/vim-indexed-search) that I'm currently using, it shows the number of matches in current buffer, and what it does, it `map / :ShowSearchIndex<CR>`, so that when you do searches in vim, it shows the number of matches in the status line.

So is there any way that I get to see the results of `:Show SearchIndex<CR>` when I'm using incsearch?

Or perhaps integrate indexed-search with incsearch? to make this plugin all we need when it comes to search in vim?

**Comment by haya14busa** [comment]
https://github.com/haya14busa/incsearch.vim/issues?q=is%3Aissue+indexedsearch+is%3Aclosed
