### ISSUE TITLE
vital-over の Modules.Digraphs を無効にしたい

### ISSUE THREAD

**Issue by osyo-manga** [haya14busa/incsearch.vim#73]
関連：https://github.com/osyo-manga/vital-over/issues/107

完全に vital-over（と、いうか Vim 側）の都合なのですが、Modules.Digraphs を組み込むと incsearch.vim の起動時に画面がちらつくという問題があるので、ユーザ側で無効にできると嬉しさがあります。

**Comment by haya14busa** [comment]
こちらにも書きましたが`<C-k>`の時に`capture`して起動時のチラつきはなくすという方向で対処したいです https://github.com/osyo-manga/vital-over/issues/107#issuecomment-93607398

**Comment by osyo-manga** [comment]
把握っ

**Comment by osyo-manga** [comment]
件の RP はﾏｯｼﾞしました。
incsearch.vim 側に組み込まれたら閉じようと思います。

**Comment by haya14busa** [comment]
とりあえず`dev`ブランチに取り込みました． `master` にもそろそろ更新しようと思ってたので多分すぐ取り込みます

**Comment by haya14busa** [comment]
master にﾏｯｼﾞしました

**Comment by haya14busa** [comment]
関連issueあったのでペタリ ref #60

**Comment by osyo-manga** [comment]
こちらでも動作することを確認しました。
ありがとうございます。

**Comment by haya14busa** [comment]
ありがとうございました
