### ISSUE TITLE
/のあとすぐにコマンドラインに入ると<Plug>(incsearch-nohlsearch)と表示される

### ISSUE THREAD

**Issue by NigoroJr** [haya14busa/incsearch.vim#82]
とても便利なプラグインをありがとうございます。デフォルト設定のVimで`/`のあとにハイライトが消えないとイラっとする程度に手放せなくなっております。

検索のあとに挿入モードに入り、すぐにノーマルモードに戻り`:`でコマンドモードに入ると、そこに`<Plug>(incsearch-nohlsearch)`と入力された状態になります。この際、

* `nohlsearch`は実行されず、ハイライトが残ったまま
* 「すぐに」というのがポイントのようで、1秒ほど待つとちゃんとハイライトが消える
* `*`で検索する場合はすぐにコマンドモードに入っても`<Plug>(incsearch-nohlsearch)`が表示されたりされなかったり(単語によって異なる)
* 挿入モードへの入り方でなったりならなかったり(`i`で入るとならないが、`A`で入るとなる、等)
* devブランチを使うと、`<Plug>(_incsearch-sethlsearch)`と表示される

ということを確認しました。また、`<Esc>`ではなく`C-o`で挿入ノーマルモードに入ってみたところ、`:nunmap <Plug>(incsearch-nohlsearch)`と表示されたため、`autoload/incsearch/util.vim`の`s:silent_feedback`かな？と思ったのですが、はっきりとは分かりません。

以下が再現する`.vimrc`です。

1. `/set<CR>`で検索する
2. `A<Esc>:`を間隔をあけずに入力する
3. コマンドラインに`<Plug>(incsearch-nohlsearch)`と表示される

```vim
set hlsearch
if has('vim_starting')
  set nocompatible
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif
call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'haya14busa/incsearch.vim'

call neobundle#end()

let g:incsearch#auto_nohlsearch = 1

map / <Plug>(incsearch-forward)
map ? <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)

map n  <Plug>(incsearch-nohl-n)
map N  <Plug>(incsearch-nohl-N)
map *  <Plug>(incsearch-nohl-*)
map #  <Plug>(incsearch-nohl-#)
map g* <Plug>(incsearch-nohl-g*)
map g# <Plug>(incsearch-nohl-g#)

filetype plugin indent on
```

**Comment by haya14busa** [comment]
@NigoroJr さん報告ありがとうございます！

似たような現象は把握していたのですが，再現手順も固まっていなくて直せていませんでした．
`dev`ブランチでも試していただいてありがとうございます！
ちょっと調査してみます :+1:

**Comment by haya14busa** [comment]
改めて考えていたら解決できることに気づいたので `dev` ブランチで実装してみました :sparkles:
もしよかったら試していただけないでしょうか?  https://github.com/haya14busa/incsearch.vim/tree/dev

**Comment by NigoroJr** [comment]
早速ありがとうございます！`dev`ブランチの変更を試してみました。
コマンドラインに文字が表示される問題は直っているみたいです:+1:
(なんだか壊そうとしているみたいで肩身が狭いのですが、)間隔をあけずに〜の操作をしたあと、`*`などでもう一回検索をすると、`hlsearch`がオフになっています。[この行](https://github.com/haya14busa/incsearch.vim/commit/110cda9f05378b9c6e7c2609a0c23ded412e9841#diff-7cd698eebe29c2fad7f22c2172fce13fR57)なのかな

**Comment by haya14busa** [comment]
> (なんだか壊そうとしているみたいで肩身が狭いのですが、)

いえいえ，自分でも再現手順がよくわかってなかったりするのでとてもありがたいです！

> 間隔をあけずに〜の操作をしたあと、set hlsearch?がnohlsearchになっています( * などでもう一回検索をすると、ハイライトされない)

これはバグですね．修正してみたので dev ブランチをアップデートして試していただけないでしょうか?
ただし，`A<Esc>:` の連続といったケースは対応していますが，他のケースに対応できたかはいまいちわからないのでもうちょっとこちらでも見てみます.

**Comment by NigoroJr** [comment]
> いえいえ，自分でも再現手順がよくわかってなかったりするのでとてもありがたいです！

そう言って頂けるとありがたいです。

> 修正してみたので dev ブランチをアップデートして試していただけないでしょうか?

うーん、やはり`nohlsearch`になってしまいます。念の為再現方法ですが、

1. `:set hlsearch?`で`hlsearch`と出ることを確認する
2. `/set<CR>`で検索する
3. `A<Esc>:`を間隔をあけずに入力する
4. `set hlsearch?`をすると`nohlsearch`と表示される

ということです。`A<Esc>:`や他のケースでやってみましたが、`nohlsearch`になります。

**Comment by haya14busa** [comment]
@NigoroJr さん

すいませんちゃんと再現しました, ありがとうございます.

そもそも実は インサートモードに入ったときにハイライトを消すという機能は #80 で入れてみた実験的なもので，
この機能を実現するためには `&hogehlsearch` の値をいじるしかありませんでした．
しかし，そもそもやはり `&hlsearch`の値をむやみに変更するのは筋が悪いと考えたこと，また個人的にはインサート時
にハイライトが消えるよりもインサートモードから抜けて動いた時に消えてほしいと思ったのでそもそもこの機能を
変更して修正を行ってみました．

お時間あるときにdevブランチを更新して確認していただけると嬉しいデス

**Comment by NigoroJr** [comment]
> インサート時にハイライトが消えるよりもインサートモードから抜けて動いた時に消えてほしい

なるほど、更新してそのままではインサートモードを抜けたときに消えなかったのですが、[この行](https://github.com/haya14busa/incsearch.vim/commit/5052435d1559d82c6c6b108f8c8a8c936f3ff1de#diff-7cd698eebe29c2fad7f22c2172fce13fR46)の1を0にすると、ちゃんとInsertLeaveでハイライトが消えました。0にすることで何か弊害はあるのでしょうか？

また、0に変更したあとに`A<Esc>:`をすぐに入力すると`:nohlsearch`が実行されなかったのですが、調べてみたところ、「間隔をあけずに」というのはターミナルVim特有(？)のもののようで、gvimでは起こりませんでした。`timeoutlen`を短くすることで一応待ち時間は短くなるのですが、他のキーバインドの待ち時間も短くなってしまうので、根本的な解決にはなりません。

**Comment by haya14busa** [comment]
> この行の1を0にすると、ちゃんとInsertLeaveでハイライトが消えました。0にすることで何か弊害はあるのでしょうか？

"インサートモードから抜けて動いた" 時に消えると便利かなと思ったので弊害はないですが意図的でした．
というのも，`/{pattern}` してから `cgn` するときなどはどこが検索結果になっていたかわかりやすいほうが便利だと思ったからです．

ただし，`InsertLeave`時にもう消えてほしいという気持ちも僕もわかるのでオプションを実装することも考えています．
しかし，移動後にハイライトが消えるだけで十分だった場合はむやみにオプションを増やしすぎてもあとから困るのでちょっと様子見中です．

@NigoroJr さんはどう思われるでしょうか?

**Comment by NigoroJr** [comment]
> 抜けて動いた時に

すみません、「動いた時に」というところを見落としていました。意図した動作だったのですね、納得です。

> /{pattern} してから cgn するときなどはどこが検索結果になっていたかわかりやすい

なるほど！私は`gn`っていう方法があったんだーという程度のVim戦闘力なのですが、オプションはあるに越したことはないと思います。と言っておきながら、私は当初の、キー入力でコマンドラインに表示されていたのが気になっていただけなので「抜けて動いたときに」で使わせていただこうと思っています :kissing_closed_eyes: しかし #80 の方のように「抜けたとき」にハイライトが消えるのを期待する方もいることを考えると、可能性としては残しておき、 @haya14busa さんのお時間があるときに、というくらいで良いと個人的には思います。十分に便利なプラグインですので。

このIssueは解決しましたので、閉じさせていただきます。ありがとうございました！

**Comment by haya14busa** [comment]
すいませんまだ master にはマージされてないので一応 reopenしておきます．がっ，僕が勝手にマスターにマージしたときに勝手に閉じるので @NigoroJr さんは特に問題無い限りは放置していただいて結構です :)

オプションは少し考えてみます

再現手順を含めた報告 & デバッグ 助かりました！ありがとうございます！

**Comment by haya14busa** [comment]
masterにマージしました．@NigoroJr さん改めてありがとうございました :+1:

**Comment by NigoroJr** [comment]
こちらこそありがとうございました！ :-)
