### ISSUE TITLE
nowrapscan 設定時に incsearch-(prev|next) と incsearch-scroll-[bf] の挙動が不審

### ISSUE THREAD

**Issue by kariya-mitsuru** [haya14busa/incsearch.vim#83]
`nowrapscan` を設定していると、`incsearch-(prev|next)` と `incsearch-scroll-[bf]` がおかしな動きをします。

具体的には、`incsearch-prev` と `incsearch-scroll-b` は、検索開始位置より前に戻ろうとすると、最後のマッチに飛んでしまい、そのまま検索を続けられてしまいます。（`?` の場合には逆）
また、`incsearch-next` と `incsearch-scroll-f` は、検索開始位置がちょうど検索文字列にマッチする場合に限って、最後のマッチで止まらずに、その次の検索で検索開始位置自体に飛んでしまいます。（説明難しい…）

`.vimrc` は以下の設定です。

```
if has('vim_starting')
  if &compatible
    set nocompatible
  endif
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'haya14busa/incsearch.vim'
call neobundle#end()
filetype plugin indent on

set nowrapscan

map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
```

`Vim` のバージョンは以下の通りです。
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May  3 2015 09:26:16)
適用済パッチ: 1-712
```

`nowrapscan` を設定した場合の `_vcount1` の補正が、検索位置より前に戻ろうとした場合や検索開始位置がマッチする場合にうまくいかない事までは追えたのですが、Vim script 力が足りなくてどうすればいいのかまではわかりませんでした。すみません…

`nowrapscan` 愛好家なので、もし直ったら嬉しいです。

**Comment by haya14busa** [comment]
@kariya-mitsuru さん 報告ありがとうございます！

> incsearch-prev と incsearch-scroll-b は、検索開始位置より前に戻ろうとすると、最後のマッチに飛んでしまい、そのまま検索を続けられてしまいます。（? の場合には逆）

これはおそらく実装当時は意図してやってしまっていました．
期待する動作としては

1. 現在の動作． `nowrapscan` だと`nowrapscan`状態の検索で動けるマッチの最後にループする
2. 検索開始位置より前に戻ろうとしても検索開始位置 or 最初のマッチで止まる
3. `nowrapscan` 関係なく前に戻れる

のどれかだと考えているのですが， @kariya-mitsuru はどう思いますか?
実は3は現在の実装では不可能です．
コード読んでいただけたならもしかしたら察していただけてるかも知れませんが, incsearch.vim は結局普通の検索コマンドのカウントをいじることで移動するので．
ただし，実装を根本的に変えれば可能であり，オペレータ待機モード時の検索以外はもっと柔軟な移動法にすることも考慮はしているのですが，互換性残しながら実装するには
時間も掛かりそうなのでムズカシイ...

3が少なくとも現在のところ不可能なので，変えるとしたら2かなと思います．

> 'wrapscan' 'ws'		切替	(既定ではオン)			*E384* *E385*
> 			グローバル
> 	検索がファイル末尾まで進んだら、ファイル先頭から再び検索する。スペリン
> 	グミスを検索する|]s|と|[s|にも適用される。

`wrapscan`はファイル末尾とは言っていますが，それをincsearch-prevに拡張すれば2の動作が自然とも考えられますし．


> また、incsearch-next と incsearch-scroll-f は、検索開始位置がちょうど検索文字列にマッチする場合に限って、最後のマッチで止まらずに、その次の検索で検索開始位置自体に飛んでしまいます。（説明難しい…）

すいません，試してみたのですがよくわかりませんでした...
適当なテストファイルとファイル起動からの再現手順みたいなものを作っていただけないでしょうか?

**Comment by kariya-mitsuru** [comment]
さっそくの返信ありがとうございます。

やっぱり 3 の動作は難しいですかぁ…
私個人の希望としては、3（`nowrapscan` でも前に戻れるけど、ファイルの先頭で止まる）→2 （検索位置まで戻ったら止まる）の順です。
理由としては、検索がくるくる回っちゃうと、どこまでがさっき見た所かがわからなくなってしまうからです。（すみません、当方鳥頭なもので…）
なので、2 でも鳥頭要件は満たせます。
3 の方が嬉しいと思った理由は、検索文字列入力中の `<Tab>` や `<S-Tab>` がノーマルモードの `n` や `N` のように使える気がしたからです。（なので、これらにも `g:incsearch#consistent_n_direction` みたいなのがあるとうれしいかも、と思ったり…）

> 適当なテストファイルとファイル起動からの再現手順みたいなものを作っていただけないでしょうか?

以下のようなファイルで、
```
1 inc
2 inc
3 inc
4 inc
5 inc
```
`3 inc` の `i` の位置にカーソルがある時に、`/inc<Tab>` とやると、`4` の行の `inc` → `5` の行の `inc` と移動しますが、この後再度 `<Tab>` を押すと `3` の行の `inc` と移動してしまい、その後は `<Tab>` を打っても先に動かなくなります。
`nowrapscan` なので `5` の行の `inc` まで移動した段階で、それ以上 `<Tab>` を打っても先に進まない（止まる）ものと思っていたのですが、もしかしてこれも意図した動作でしょうか。
（多分、`autoload/incsearch.vim` の 397 行目で得られる `max_count` が、カーソル位置が検索文字列にマッチする場合にその文字列もカウントしているためだと思うのですが…）
なお、`?` の場合にはそのような動きはしません。

**Comment by haya14busa** [comment]
> 私個人の希望としては、3

ですよねー．僕も希望としては3を実装したいのですが，incsearch.vimはデフォルトでもドットリピートなどなどデフォルトの挙動に基本的に準拠するという思想上実装がなかなかハードなんですよね...

とりあえずは2の 検索開始位置より前に戻ろうとしても最初のマッチで止まる(こちらのほうが簡単) に修正して，
いづれ(いづれ)もっとincsearch.vimが柔軟な移動方法を提供したときに3が実装されるのを気長に期待せずに待っていただけるというのが落とし所かなぁと思います．
なるべくガンバリマス！

> (多分、autoload/incsearch.vim の 397 行目で得られる max_count が、カーソル位置が検索文字列にマッチする場合にその文字列もカウントしているためだと思うのですが…）

把握しました！おそらく原因もおっしゃるとおりですし完全にバグなので修正します．ありがとうございます

**Comment by haya14busa** [comment]
2の 検索開始位置より前に戻ろうとしても最初のマッチで止まるに仕様変更かつ，カーソル位置にいた場合のバグを修正しました．

spec修正してfail: https://travis-ci.org/haya14busa/incsearch.vim/builds/65201920
コード修正: https://travis-ci.org/haya14busa/incsearch.vim/builds/65202178

def ブランチ https://github.com/haya14busa/incsearch.vim/tree/dev に修正を取り込んだのでお時間あるときに確認をよろしくお願いします

**Comment by kariya-mitsuru** [comment]
> 3が実装されるのを気長に

2 の方を対応して頂けるのであれば 3 の方は全然大丈夫です！

> 確認をよろしくお願いします

dev ブランチ確認しました。
前に戻ろうとすると止まるのは確認できたのですが、`/` 時の `<Tab>` で行き過ぎちゃう問題の方が今度は `/` の方が直って `?` の方が変になってる感じです。
`?` の時の `count_pattern` の引数 `from` が前と違ってカーソル位置になったようなので、カウントが 1 つ増えてるようです。（前は `from` がカーソルの一つ前だった）

あと、`?` の場合も先頭を検索対象外にしていますが、そうするとファイルの最初がマッチする場合にカウントが 1 つ減っちゃってます。（上記の問題と併せて、 `?` でファイルの先頭がマッチする場合には一見正しい動きに見える…）

お手すきの時にでも見てみてください。

**Comment by haya14busa** [comment]
fail: https://travis-ci.org/haya14busa/incsearch.vim/builds/65222172
success: https://travis-ci.org/haya14busa/incsearch.vim/builds/65222208

ｱｱｯ....ダメfixかつテストしてないというダメさ加減でした....反省 :sob: 
報告ありがとうございます，同様にdevブランチにて修正しました．

よろしければ確認おねがいしますっ

**Comment by kariya-mitsuru** [comment]
すばやいっっっ！！！

ありがとうございます。
少なくとも私のわかる範囲では想定通りの動きをしています！

お忙しいところありがとうございました！！！

**Comment by haya14busa** [comment]
報告 & デバッグ ありがとうございました！
ちょっと別issueのやつとか同時並行で dev ブランチにﾏｯｼﾞしていってるのですぐにはmasterに反映できないですが，近いうちに master にﾏｯｼﾞさせていただきます~

**Comment by haya14busa** [comment]
masterにマージしました．
ありがとうございましたっ！:sparkles:
