### ISSUE TITLE
I need to preload the incsearch code.

### ISSUE THREAD

**Issue by x1024** [haya14busa/incsearch.vim#85]
The first time when I search, all of the incsearch code seems to be loaded. This means that there is a delay of 0.5-1.0s when I press "/".

I'd like to get rid of that, and would like to preload that code on Vim startup. Is there a good way of doing that?

**Comment by jeromedalbert** [comment]
Same problem here

**Comment by haya14busa** [comment]
I improved first loading time instead of providing preload api #112. Can you update the plugin and try it again?

**Comment by x1024** [comment]
Yes, this new update makes using the plugin feel completely natural. Thank you very much.
