### ISSUE TITLE
Keep cursor highlight even after pressing n/N to next/previous matched position

### ISSUE THREAD

**Issue by kevin4fly** [haya14busa/incsearch.vim#87]
As the demo shows, we are able to highlight the cursor by adding `highlight IncSearchCursor ctermfg=0 ctermbg=9 guifg=#000000 guibg=#FF0000`. However, the cursor cann't keep highlight after we press `n/N` to search next/previous matched position. If there are many matched short text, moving the cursor to next or previous is pretty annoying. So could you please help to add this feature? Thanks in advance!

**Comment by haya14busa** [comment]
sorry for the late reply.

You can create custom n/N wrapper mapping to highlight cursor position. I don't have any plan to add it to incsearch.vim
