### ISSUE TITLE
consistent_n_direction not working with # (sharp)

### ISSUE THREAD

**Issue by dan-santana** [haya14busa/incsearch.vim#90]
the when using the following mappings:

```
let g:consistent_n_direction = 1
map #  <Plug>(incsearch-nohl-#)
```

It is not going in the right direction with `n`, instead it is still moving backward (and forward with `N`).

**Comment by pwntester** [comment]
same problem here

**Comment by haya14busa** [comment]
I'm sorry for the late reply.  Please use `g:incsearch#consistent_n_direction` instead of `g:consistent_n_direction`.

**Comment by dan-santana** [comment]
I'm sorry, I posted the wrong code. Actually it was set as `let g:incsearch#consistent_n_direction = 1` but it still didn't make any difference when using `<Plug>(incsearch-nohl-#)` it still goes backward with `n` and forward with `N` with the latest plugin version.
