### ISSUE TITLE
<Plug>(incsearch-backward) is not find '?'

### ISSUE THREAD

**Issue by DeaR** [haya14busa/incsearch.vim#92]
`<Plug>(incsearch-backward)?`
not find (OK)

`<Plug>(incsearch-backward)\?`
jump, but not find (NG)

**Comment by haya14busa** [comment]
Thanks I confirmed this bug. I'll look into it.

**Comment by DeaR** [comment]
流石に私の英語力が足りないのでここから日本語

この辺りの動作も再現すると同時に
```
							*/\?*
\?	\= と同じ。"?" コマンドによる後方検索では使えません。
	{Vi にはありません}
```
も関わってくるので`/``?`の先入観のない人には
`/`と同様の表現で前方向な別の機能もアリかもなんて思ったりはします
enhancementな話しなので別問題ですけどね

**Comment by haya14busa** [comment]
> /と同様の表現で前方向な別の機能

うーむ, すいません，この部分がよくわからなみです．

**Comment by DeaR** [comment]
標準の`/`の時と同様に
`\/`で`/`にmatch(標準の`?`では`/`でmatch)
`?`で`?`にmatch(標準の`?`では`\?`でmatch)
`\?`で正規表現の`\?`(標準の`?`では`\=`で代替)

今まで標準のを使ってて慣れてるので気にしてないですが
`/`と`?`でそれらの記号が出てくる場合、検索文字列が差異が出る
実際どうでもいい余談なのは言うまでもないです

**Comment by haya14busa** [comment]
あーどっちだろうが`\`つけて統一するって感じですかね．
ただ，できるだけ正規表現いじってやると`\v`とかのフラグの問題もあってつらいので少なくとも標準ではやらないかなという感じです． converter機能で対応するとかはありそう

**Comment by DeaR** [comment]
確かにconverterでの実装が理に適ってる感じですね

如何せん'面白い'の域を抜けなく、使ったら余計混乱しそうな機能で使う人が居なさそうな戯言です
実際、報告するのに`?`を`\?`にしたり`\\?`にしたりした時にふと改めて意識しただけですし

**Comment by haya14busa** [comment]
バグについては修正しました。遅くなってたいへんすいません。
報告ありがとうございましたっ！
