### ISSUE TITLE
Cursor does not look OK in Vim for Windows and Neovim for Mac OS

### ISSUE THREAD

**Issue by saaguero** [haya14busa/incsearch.vim#93]
This happens both in Vim for Windows (ConEmu) as well as Neovim in Mac OS (iTerm):

![screen shot 2015-08-10 at 22 44 16](https://cloud.githubusercontent.com/assets/2459621/9188356/ab0a6882-3fb1-11e5-9675-867fd890b895.png)

In graphical gVim as well as mvim it looks correctly:

![screen shot 2015-08-10 at 22 46 03](https://cloud.githubusercontent.com/assets/2459621/9188352/a375da7a-3fb1-11e5-9657-c0d9d3b53bd2.png)

**Comment by haya14busa** [comment]
Thanks for the report but it's duplicated with #79, so I closed this issue

**Comment by gelguy** [comment]
In ConEmu, `set t_ve=` does not work. I believe this is due to ConEmu not recognising the empty escape code. In ConEmu, the way to hide the cursor is the escape code `<Esc>[25l`.

```vim
    if !empty($CONEMUBUILD)
      set t_ve=[25l
    else
      set t_ve=
    endif
```

vital-over has to be changed to include this in order to support ConEmu.
