### ISSUE TITLE
Can't turn off "consistent_n_direction"

### ISSUE THREAD

**Issue by edanm** [haya14busa/incsearch.vim#95]
Hey,

I can't seem to get "consistent_n_direction" to turn off.

E.g. even when setting it to 0, then doing a backwards search like "?something", then pressing "n", will match the next match forward in the document instead of backwards.

Any thoughts? Am I doing something wrong?

**Comment by phphong** [comment]
same problem here. I found out that this bug is introduced from commit 6640b8a

**Comment by arkwright** [comment]
Same problem here. `let g:incsearch#consistent_n_direction = 0` has no effect. Removing the incsearch plugin corrects the problem.

**Comment by haya14busa** [comment]
I'm really sorry for the late reply.
@djjcast kindly created PR to fix this problem.

It seems this problem is solved. Please reopen if not.
Thank you!

**Comment by edanm** [comment]
Awesome, thanks so much!
